driver:
  name: dokken
  privileged: true # needed for Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

- name: amazonlinux
  driver:
    image: amazonlinux:2017.09

suites:
- name: default
  run_list:
  - recipe[yum-atomic::default]
