source 'https://rubygems.org'

gem 'berkshelf'
gem 'rake'
gem 'rubocop', '~> 0.24'
gem 'foodcritic', '~> 3.0'
gem 'chefspec', '~> 4.0'
gem 'serverspec', '~> 0.14.2'
gem 'fauxhai'
gem 'test-kitchen', '~> 1.2'
gem 'kitchen-vagrant', '~> 0.11'
